// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnj3JBcLbfS7lyd4LD6x10qyLYhjeGpLI',
    appId: '1:994836624683:web:d85959dd4760b5ac22016e',
    messagingSenderId: '994836624683',
    projectId: 'mapping-tool-6947c',
    authDomain: 'mapping-tool-6947c.firebaseapp.com',
    storageBucket: 'mapping-tool-6947c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAavmndX3ySqs9r8U_lTjiXCe75tMotckE',
    appId: '1:994836624683:android:dcf765cc3aa4271b22016e',
    messagingSenderId: '994836624683',
    projectId: 'mapping-tool-6947c',
    storageBucket: 'mapping-tool-6947c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fPpDU6ybGcxlyRXO_dhyxwBYmQBVO5c',
    appId: '1:994836624683:ios:44def8e6c8d4dde422016e',
    messagingSenderId: '994836624683',
    projectId: 'mapping-tool-6947c',
    storageBucket: 'mapping-tool-6947c.appspot.com',
    iosBundleId: 'com.example.mapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fPpDU6ybGcxlyRXO_dhyxwBYmQBVO5c',
    appId: '1:994836624683:ios:44def8e6c8d4dde422016e',
    messagingSenderId: '994836624683',
    projectId: 'mapping-tool-6947c',
    storageBucket: 'mapping-tool-6947c.appspot.com',
    iosBundleId: 'com.example.mapping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnj3JBcLbfS7lyd4LD6x10qyLYhjeGpLI',
    appId: '1:994836624683:web:56f5969fc6cc804a22016e',
    messagingSenderId: '994836624683',
    projectId: 'mapping-tool-6947c',
    authDomain: 'mapping-tool-6947c.firebaseapp.com',
    storageBucket: 'mapping-tool-6947c.appspot.com',
  );
}
